### ISSUE TITLE
Engine: concrete idents: bad names for primitives things

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#1013]
cc @cmester0

**Comment by franziskuskiefer** [comment]
@W95Psp this needs more detail. Please add more information or close it.

**Comment by W95Psp** [comment]
I recall I opened this issue while we where chatting indeed, @cmester0.
Shall we close then?

**Comment by franziskuskiefer** [comment]
@W95Psp What's the state here? Is this needed or can it be closed?

**Comment by W95Psp** [comment]
Let's close for now, I think this is mostly about how to move from the manual core library to the annotated one.
