### ISSUE TITLE
CLI subcommands: flatten a bit, drop `into`

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#103]
`cargo hax into BACKEND` is a bit long, `cargo hax BACKEND` is shorter

Pros for `into`:
 - it namespaces properly subcommands so that we can have subcommand-specific options and flags (e.g. `cargo hax lint LINTER` takes no `output-dir`, while `cargo hax into BACKEND` does, and `cargo hax json` takes a `output-file`)
 - if we have a `lint` subcommand, I feel like that's nice to have a `into` (or `extract` or `translate` or whatever) subcommand as well, I feel like that makes the CLI more comprehensive & tidy

Cons:
 - `hax` already stands for high assurance **translate**/**export**/something-like-this, thus `cargo hax into/translate/whatever` is redundant
 - `circus hax into BACKEND` is three nested subcommands, this is a lot

Propositions:
 - Collapse both `into` and `lint`
 - Collapse only `into`
 - Make typing `into` optional

**Comment by W95Psp** [comment]
What should we do here?
Wdyt @cmester0 @franziskuskiefer @karthikbhargavan?

**Comment by franziskuskiefer** [comment]
Good question. I don't have a strong opinion on this.
I'm leaning towards `cargo hax fstar` etc. But there are good reasons for both.
Unless there's a good reason to change it, I'd vote for keeping it as is for now, until we have cycles to reevaluate.
