### ISSUE TITLE
Trait implementation of Option<T> not working

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#1125]
```rust
trait Encode {
    fn encode();
}

impl<T: Encode> Encode for Option<T> {
    fn encode() {
        T::encode();
    }
}

```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar+tc/ce1554f401/gist=36bf714b47c0d9fc9b555536894ee648)

**Comment by W95Psp** [comment]
This is related to https://github.com/hacspec/hax/issues/616. The problem here is that `encode` is translated as a field in a record: we rather need `encode` to be a top-level function, so that the standard recursivity mechanism kicks in.

**Comment by karthikbhargavan** [comment]
This appears to work with this workaround:

https://hax-playground.cryspen.com/#fstar/ce1554f401/gist=9e17801a8e0c2937e4116b8ac9993d15

Should be done automatically by:
https://github.com/hacspec/hax/issues/789

**Comment by W95Psp** [comment]
Closing in favor of #789.
