### ISSUE TITLE
i8::MIN / -1 panics but verifies

### ISSUE THREAD

**Issue by ambiso** [hacspec/hax#1155]
The following function verifies with the condition that `y != 0`, but I believe it should not, since it can panic.

```rust
// Read more about `requires` here: https://hacspec.org/book/tutorial/panic-freedom.html
#[hax_lib::requires(y != 0)]
fn d(x: i8, y: i8) -> i8 {
    x / y
}


```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar+tc/1c5e17c9ce/gist=64420f57c01aeff58f71fe6207aebd68)

When calling this function with `i8::MIN` and `-1` it overflows:

```rs
fn d(x: i8, y: i8) -> i8 {
    x / y
}

fn main() {
    println!("{}", d(i8::MIN, -1));
}
```

```
$ cargo run
   Compiling hax_repro v0.1.0 (/home/projects/dump/hax_repro)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/hax_repro`
thread 'main' panicked at src/main.rs:2:5:
attempt to divide with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

(See also https://blog.regehr.org/archives/887 and https://mastodon.social/@regehr/113564124872096630 )

**Comment by ambiso** [comment]
More direct repro:

```rs
#[allow(unconditional_panic)]

// Read more about `requires` here: https://hacspec.org/book/tutorial/panic-freedom.html
#[hax_lib::requires(true)]
fn d() -> i8 {
    (-128i8) / (-1i8)
}
```

[Playground](https://hax-playground.cryspen.com/#fstar+tc/1c5e17c9ce/gist=8e15d79adf9c04b4f75fa18561e1c243)

**Comment by ambiso** [comment]
I assume this condition would need to be updated?
https://github.com/hacspec/hax/blob/1c5e17c9ceee5adede0f4ea7f68bb3d8337f33a0/proof-libs/fstar/rust_primitives/Rust_primitives.Integers.fsti#L241

**Comment by karthikbhargavan** [comment]
Correct: this function has an assume whereas it should have a pre-condition.
We have been working on a new version of the library model which does not
have these assumes, but we should fix this.
