### ISSUE TITLE
Frontend: add a `DefKind` on `DefIdContents`

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#1162]
Names extracted by the frontend will be much nicer to work with with a `DefKind` attached.
We want to add a field of type [DefKind](https://doc.rust-lang.org/stable/nightly-rustc/rustc_hir/def/enum.DefKind.html) on the struct `DefIdContents`.

cc @Nadrieril, I think that's something you wanted to do as well

**Comment by Nadrieril** [comment]
Yep, sounds good 👍
