### ISSUE TITLE
AST: support comments & translate them from Rust (only the `///` ones which are actually attribtues)

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#117]
- [x] translate comments in frontend
 - [x] transport comments throughout the engine
 - [x] make the backends output comments
    - [ ] coq
    - [x] F*
    - [x] Generic printer

We should also have a settings to skip those attributes.

**Comment by franziskuskiefer** [comment]
Is there a particular reason to translate these doc comments but not others?

**Comment by W95Psp** [comment]
Well, I don't think other comments are present anywhere even in the surface AST :/
So I think there is no reliable way to support them

**Comment by franziskuskiefer** [comment]
All doc comments are attributes afaik, see https://doc.rust-lang.org/reference/comments.html#doc-comments.

But I don't know if we can get others ...

**Comment by W95Psp** [comment]
Oh, yes, I meant doc atrributes in general, not just ///.
Yeah, others are not available at all in the surfave AST I think, so I think we should not support them (otherwise we'll end up doing very nasty and non robust things)
