### ISSUE TITLE
Missing type ascription in match scrutinee with array indexing

### ISSUE THREAD

**Issue by ROMemories** [hacspec/hax#1207]
While I would expect it to, the following snippet does not typecheck:

```rust
const FOO_SIZE: usize = 5;

const FOO: [u8; FOO_SIZE] = [0, 0, 0, 0, 0];

#[hax_lib::requires(i < FOO_SIZE)]
fn foo(i: usize) {
    let _ = match FOO[i] {
        0xff => 42,
        _ => 41,
    };
}
```

[view on playground](https://hax-playground.cryspen.com/#fstar/9d78af6a1a/gist=83aa686febdca1aa1d35bdb7b8e7788c)

However, when replacing the `match` with an `if`, it does, as expected:

```rust
const FOO_SIZE: usize = 5;

const FOO: [u8; FOO_SIZE] = [0, 0, 0, 0, 0];

#[hax_lib::requires(i < FOO_SIZE)]
fn foo(i: usize) {
    let _ = if FOO[i] == 0xff {
        42
    } else {
        41
    };
}
```

[view on playground](https://hax-playground.cryspen.com/#fstar/9d78af6a1a/gist=628b4d1a9aa9414f1f6d8fdf40c870ee)

It seems that the array indexing in the first case is missing a `<: u8` type ascription, which gets generated only in the `if` case.

Is this some specific interaction between the `match` and array indexing, or just the symptom of something else?

Credits go to @chrysn for finding this.

**Comment by franziskuskiefer** [comment]
This appears to be related to #1170.

**Comment by karthikbhargavan** [comment]
Thanks, this is a good catch. It is indeed a missing ascription which is confusing the typeclass resolution in F*.
The error message could also be better.

**Comment by maximebuyse** [comment]
The ascriptions we insert are in nested function calls (which is what makes it works in the `if` case, and in `let` bindings. We should add an ascription for `match` scrutinees.
