### ISSUE TITLE
error[CE0001]: Or on enums is not implemented

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#161]
The following code

```rust
pub enum Values {
    Val1,
    Val2,
}

pub fn or(input: Values) -> bool {
    matches!(input, Values::Val1 | Values::Val2)
}
```

fails with

```
error[CE0001]: Diagnostics.Context.ThirImport: something is not implemented yet.
               Or
   --> src/lib.rs:175:21
    |
175 |     matches!(input, Values::Val1 | Values::Val2)
    |                     ^^^^^^^^^^^^
```

**Comment by mzacho** [comment]
Are you currently looking at this @W95Psp? Otherwise I think it might be a good initial issue for me to work on :)

**Comment by W95Psp** [comment]
Hi @mzacho, sorry I had a busy day, only replying now.
No, I'm not looking at this currently!
That sounds like a great idea :smiley: 
Feel free to ping me here or on zulip if you need to chat about some of the internals!

**Comment by mzacho** [comment]
No worries - awesome, will do, thanks!
