### ISSUE TITLE
New subcommand `cargo hax check`

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#173]
The subcommand `check`, just like `into` or `lint`, runs on a selection of crates.

For each selected crate `CRATE`, `check BACKEND`:
 1. make sure the current crate was extracted (maybe just a check the folder `CRATE-PATH/proof/BACKEND/extraction` exists)
 2. produces a list of paths for the fstar/coq/BACKEND modules from the dependencies of `CRATE`:
    - lists all the dependencies (indirect ones as well as direct ones);
    - make sure `cargo` downloaded the dependencies;
    - figure out where each dependency is located;
    - filter out those that have no `proof` directory;
    - build up a list of paths pointing to the `proof/BACKEND/{extraction,model,.}` directory of each dependency.
 3. calls `make` in folder `CRATE-PATH/proof/BACKEND/`, with `HAX_BACKEND_PATHS` env var set.

### Note about selecting crates
The selection is made by the user:
 - with `-C -p somepackage ;`, `-C --manifest-path some/path/to/Cargo.toml`, or any other option `cargo build` accepts.
 - or according to the current folder the command was ran into.

`check` however doesn't hook inside rustc, thus we need to figure out what crates are selected.
I think we can use something in the spirit of:
`cargo build OPTIONS_PASSED_WITH_C -Z unstable-options --build-plan | jq '.invocations | .[] | select(.env.CARGO_PRIMARY_PACKAGE) | .env.CARGO_MANIFEST_DIR'`

**Comment by franziskuskiefer** [comment]
Please add some description to what this is doing.

**Comment by W95Psp** [comment]
done, updated it with a plan on how to do this precisely

**Comment by franziskuskiefer** [comment]
🙏🏻  Thanks

The `make` command should maybe be defined somewhere (in case it's not make).

Note that the `build.rs` build has `CARGO_PRIMARY_PACKAGE` set as well.
