### ISSUE TITLE
Memory issues in OCaml build

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#197]
The build of the engine requires too much memory and runs out of memory on some machines because opam spawns too many processes.

To fix this:
 - [x] the `setup.sh` should start with fewer jobs and a `-j` option for faster builds should be added.
The readme needs to be updated with this information.

In addition:
 - [x] the build should be checked to understand why it requires so much memory.

**Comment by W95Psp** [comment]
Fixed by #504!
