### ISSUE TITLE
Traits: compute explicit implementation expressions

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#20]
Consider the following code:
```rust
trait Show {
    fn show(self) -> String;
}
// Let's name this impl. `ShowStr`
impl Show for &str {
    fn show(self) -> String {
        self.to_string()
    }
}
// Let's name this impl. `ShowU8`
impl Show for u8 {
    fn show(self) -> String {
        format!("{}", self)
    }
}
// Let's name this impl. `ShowVec`
impl<T: Show, U: Show> Show for (T, U) {
    fn show(self) -> String {
        format!("({}, {})", self.0.show(), self.1.show())
    }
}
```

The expression `(1, "a").show()` is for now translated as a call to the method `show` of the typeclass/trait `Show` with argument `(1, "a")`.
Some backends might have no typeclasses or traits, and some (like F*) have typeclasses mechanisms whose inference mechanism is not great.

Thus, we need the frontend to derive the implementation expressions (i.e. `ShowVec ShowU8 ShowStr` for `(1, "a").show()`).

-----------------
**Edit:** we've got another constraint.  
In the engine, we often transform some patterns (i.e. mutation, loops) into function calls that are trait methods.
Thus, maybe we should *not* do impl resolution in Rust, but on the OCaml side. Or do both: we should anyway export as much info in the frontend, but we'll need to do some impl resolution in the engine.

----------------
Status: @sonmarcho has some great prototype for that :tada: 

----------------
Status (2023-12-21): this was done by #249 on the frontend side, and will be completed in the engine by #372

**Comment by spitters** [comment]
Is there a good comparison between the type class implementations in F*,
Coq and lean?
https://www.fstar-lang.org/tutorial/book/part3/part3_typeclasses.html

**Comment by spitters** [comment]
I believe there is some work on adding type classes to Easycrypt. Do you
happen to know more?

**Comment by spitters** [comment]
The F* documentation hints that they got that from Coq (dep records +
eauto proof search).

**Comment by W95Psp** [comment]
Oh, right, that makes sense then!

**Comment by W95Psp** [comment]
The extraction of impl expression from Rustc was done in the backend by #249
