### ISSUE TITLE
Function order matters

### ISSUE THREAD

**Issue by cmester0** [hacspec/hax#203]
A lot of the backends requires the rust functions to come in the correct order based on dependency, so we should either reorder functions or add a function signature/header section before the actual implementation.

We could also just reject code where functions are in an incorrect order.

**Comment by W95Psp** [comment]
I agree, and I would like to add a few things.

## Examples
Rust `mod`s are really about namespacing. And Rust allows wild namespaces: a function can be mutually recursive **across** modules:
```rust
mod a {
    pub fn f (x: u8) -> u8 {
        if x < 0 { x } else { super::b::f(x - 1) }
    }
}
mod b {
    pub fn f (x: u8) -> u8 {
        if x < 0 { x } else { super::a::f(x - 1) }
    }
}
```

In this case, we should probably transform to:
```rust
mod bundle_a_b {
    pub fn a_f (x: u8) -> u8 {
        if x < 0 { x } else { b_f(x - 1) }
    }
    pub fn b_f (x: u8) -> u8 {
        if x < 0 { x } else { a_f(x - 1) }
    }
}
mod a { pub fn f (x: u8) -> u8 { super::bundle_a_b::a_f(x) } }
mod b { pub fn f (x: u8) -> u8 { super::bundle_a_b::b_f(x) } }
```

We can also write something like: 
```rust
fn f() {}
mod b {
    use super::*;
    pub fn g() {super::f ()}
}
fn h() { b::g() }
```

Here we have:
 - a dependency from `b` to `a` (`a::b::g` uses `a::f`);
 - a dependency from `a` to `b` (`f::h` uses `a::b::g`)

In this case, we can either:
 - make a bundle for `f`, `g` and `h` just like above;
 - make a bundle only for `f` and `g` and use that in the rest of the top-level module.


## Solution
We want our module-level dependency graph to be a tree.
For this, we should identify every group of items that spans across multiple modules and isolate them in newly named modules.

**Comment by karthikbhargavan** [comment]
Alternatively, another extreme would be to get rid of all modules and flatten everything to the top-level, using module names as prefixes to disambiguate item names. This may of course be quite large and ugly for large crates with hundreds of modules.

**Comment by W95Psp** [comment]
Yeah, but for Core for instance, we currently end up with 110k LoC of F* across all modules. (I guess that's because of things being factorized with macros on Rust side)
I don't see F* not crashing entirely on such a big 110k LoC module :smile:

**Comment by W95Psp** [comment]
The ordering of functions has been solved by https://github.com/hacspec/hax/pull/249

Related: #379
