### ISSUE TITLE
Rust playground

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#26]
~~Have a fork of the [rust playground](https://github.com/rust-lang/rust-playground) with an option for running Hax for a given backend. (I have some WIP proto, but it's very outdated)~~

~~Another option would be to write something from scratch, maybe that would be easier.~~

Make a custom playground dedicated to running Hax.

I already have a prototype for this. Would need half a day to make it work, and a bit more to make it nice.

**Comment by franziskuskiefer** [comment]
https://hax-playground.cryspen.com/
