### ISSUE TITLE
Port specifications from repository `hacspec/specs`

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#28]
- [ ] `tls_cryptolib` (fstar: ❌CE0001[^1], coq: ❌CE0001[^1])
 - [x] `hacspec-curve25519` (fstar: ✅, coq: ✅)
 - [x] `hacspec-chacha20` (fstar: ✅, coq: ✅)
 - [x] `hacspec-ristretto` (fstar: ✅, coq: ✅)
 - [x] `hacspec-linalg` (fstar: ✅, coq: ✅)
 - [ ] `hacspec-merlin` (fstar: ❌CE0002[^2], coq: ❌CE0002[^2])
 - [x] `hacspec-poly1305` (fstar: ✅, coq: ✅)
 - [x] `hacspec-chacha20poly1305` (fstar: ✅, coq: ✅)
 - [x] `hacspec-gimli` (fstar: ✅, coq: ✅)
 - [x] `hacspec-sha1` (fstar: ✅, coq: ✅)
 - [x] `hacspec-sha256` (fstar: ✅, coq: ✅)
 - [x] `hacspec-sha3` (fstar: ✅, coq: ✅)
 - [x] `hacspec-ntru-prime` (fstar: ✅, coq: ✅)
 - [x] `hacspec-riot-bootloader` (fstar: ✅, coq: ✅)
 - [x] `hacspec-riot-runqueue` (fstar: ✅, coq: ✅)
 - [x] `hacspec-hmac` (fstar: ✅, coq: ✅)
 - [x] `hacspec-hkdf` (fstar: ✅, coq: ✅)
 - [x] `hacspec-p256` (fstar: ✅, coq: ✅)
 - [x] `hacspec-bls12-381` (fstar: ✅, coq: ✅)
 - [x] `hacspec-ecdsa-p256-sha256` (fstar: ✅, coq: ✅)
 - [x] `hacspec-aes` (fstar: ✅, coq: ✅)
 - [x] `hacspec-aes-jazz` (fstar: ✅, coq: ✅)
 - [x] `hacspec-gf128` (fstar: ✅, coq: ✅)
 - [x] `hacspec-aes128-gcm` (fstar: ✅, coq: ✅)
 - [x] `hacspec-bls12-381-hash` (fstar: ✅, coq: ✅)
 - [x] `hacspec-ed25519` (fstar: ✅, coq: ✅)
 - [x] `hacspec-edwards25519` (fstar: ✅, coq: ✅)
 - [x] `hacspec-edwards25519-hash` (fstar: ✅, coq: ✅)
 - [x] `hacspec-edwards25519-ecvrf` (fstar: ✅, coq: ✅)
 - [x] `hacspec-rsa-pkcs1` (fstar: ✅, coq: ✅)
 - [x] `hacspec-bip-340` (fstar: ✅, coq: ✅)
 - [x] `hacspec-rsa-fdh-vrf` (fstar: ✅, coq: ✅)
 - [x] `hacspec-xor` (fstar: ✅, coq: ✅)

[^1]: ``(Diagnostics.Context.Phase FunctionalizeLoops): something is not implemented yet.
Loop without mutation?``
[^2]: ``Fatal error: something we considered as impossible occurred! Please report this by submitting an issue on GitHub!
Details: Import_thir.UnsafeBlock``

**Comment by W95Psp** [comment]
Shall we close this issue? Wdyt @franziskuskiefer?

**Comment by franziskuskiefer** [comment]
Yes, let's close this.
We still don't have hacspec/specs#3, hacspec/specs#10, or hacspec/specs#12 merged to really start transitioning. But we can track this over there.
