### ISSUE TITLE
Lib macros: general improvements

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#297]
- [x] make forall and exists usable
 - [ ] generate `debug_assert!`s for ensures and requires (on demand, otherwise we'll run in lifetime issues)
 - [ ] revive `decreases` (requires #296)
 - [ ] revive `modeled_by`
 - [ ] `decreases` clauses: clarify what is F\* specific

Also, concerning forall/exists + debug_asserts, there's a clash, we need to do something. My take is that if the user wants to have the pre/postcondition as a debug assert, then forall&exists are not available. Note having debug_asserts is also an issue for lifetimes.

On that topic, this PR comment is relevant:
              I'm not sure I understand what this is supposed to do and why it always returns `true`.
              Also wouldn't it be nice to be able to run these in Rust as well in debug builds to have them checked at least at runtime for tests?

_Originally posted by @franziskuskiefer in https://github.com/hacspec/hax/pull/244#discussion_r1365473803_

**Comment by franziskuskiefer** [comment]
> My take is that if the user wants to have the pre/postcondition as a debug assert, then forall&exists are not available. Note having debug_asserts is also an issue for lifetimes.

Can you elaborate on what the issue is?
