### ISSUE TITLE
Coq backend: can generate invalid type references

### ISSUE THREAD

**Issue by mzacho** [hacspec/hax#303]
Running `cargo hax into coq` on

```rust
pub struct Foo {}
pub fn bar(x: Foo) {}
```

yields

```coq
Record t_Foo : Type :={}.

Definition bar (x : t_Foo_t) : unit := tt.
```

i.e. the reference `t_Foo_t` is invalid.

I don't have the slightest idea of what's going on in the BE yet, but I'm guessing that stripping "_t" from https://github.com/hacspec/hax/blob/main/engine/backends/coq/coq/coq_backend.ml#L174 breaks stuff?

**Comment by franziskuskiefer** [comment]
@cmester0 can you guide @mzacho here to the right solution?
