### ISSUE TITLE
Feature gate (nested?) disjunctive patterns

### ISSUE THREAD

**Issue by mzacho** [hacspec/hax#306]
Not all BEs support disjunctive patterns/ nested disjunctive patterns. E.g. F* (I believe) supports disjunctive patterns but according to @W95Psp not nested disjunctive patterns.

Right now #304 throws an error in `engine/backends/fstar/fstar_backend#337`, and thus disallows (nested *and* top-level) disjunctive patterns, however a better solution is to add `disjunctive_pat` to `features.ml` and `POp` in `ast.ml`.

**Comment by W95Psp** [comment]
You're pointing out something interesting: only nested disjunctive patterns are not possible in F*.
So maybe feature gating those doesn't make sense (since the new construct you added reflects both nested and "simple" disjunctive pats)... I'm not too sure what to think here.

**Comment by W95Psp** [comment]
Let's not feature-gate that, that would bring little value and require some (a bit painful / ugly) encoding
