### ISSUE TITLE
Incorrect order for Deps.sort

### ISSUE THREAD

**Issue by cmester0** [hacspec/hax#379]
The following piece of code
```rust
pub trait Foo {
    const c : u32;
}

pub struct foo {}
impl Foo for foo {
    const c : u32 = 17;
}

type F = foo;

pub fn bar(random: u32) -> u32 {
    random % F::c
}
```
gets sorted incorrectly, as the `bar` function is moved before the impl block. If possible we should probably keep the order of the original program instead of moving functions earlier, if there are no conflicts in the dependency graph.

**Comment by cmester0** [comment]
This issue is related to #375 as the graph is not getting an edge, since the concrete idents are not equal.

**Comment by W95Psp** [comment]
Hi Lasse, thanks for the bug report!
That's indeed related to #375, and also to #372, which I have to debug.
Gonna try to look at that soon.

**Comment by W95Psp** [comment]
Hey, this should be fixed now, impl expressions are taken into account for the dependency analysis.
Can you check if that works for you on main and close if it's the case? Thanks!
