### ISSUE TITLE
Make the engine compile on Windows + CI

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#401]
Last time I checked, the engine was not compiling on Windows, but I checked only through GitHub Actions. Testing with a Windows machine or a VM would be much more effective.

We should also add compilation and tests under Windows to the CI: #4

**Comment by W95Psp** [comment]
@franziskuskiefer shall we close this one?
I think we should either close it or plan work on that, otherwise the issue will just stay forever. We have no current need for Windows build, so I don't see this being a priority, and I don't see anyone that work on hax just pick that as a fun issue or something 😅

**Comment by franziskuskiefer** [comment]
Closing this for now.
