### ISSUE TITLE
ProVerif goal: Noise protocol example extraction

### ISSUE THREAD

**Issue by jschneider-bensch** [hacspec/hax#414]
In a [branch of `hacspec/specs`](https://github.com/hacspec/specs/tree/noise/noise-kkpsk0) there's a hacspec version of the KKpsk0 noise protocol pattern that @karthikbhargavan was working on. It's already pretty much in the code style we would expect the ProVerif backend to be able to handle, which makes it an ideal intermediate goal before moving from toy example to more complicated code bases.

- [x] Sanity: extraction works
- [x] Translate early returns and `?` to failures
- ~~Separate Protocol flow from party internals~~
- [ ] generate top-level process; easier in this case since there always two parties (#426)

We split the remaining work into the following subtasks:
- [ ] #446
- [ ] #447
- [ ] #448
- [ ] #449
- [ ] #450

**Comment by franziskuskiefer** [comment]
Closed in favour of the sub-issues in https://github.com/hacspec/hax/issues/414#issue-2063953621
