### ISSUE TITLE
`unsafe` blocks

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#417]
We don't plan to support `unsafe` blocks.

**Comment by franziskuskiefer** [comment]
Great timing of the bot, this should also go on https://github.com/cryspen/home/issues/95 I suppose @W95Psp

**Comment by W95Psp** [comment]
Basic support was added in #867.
I suppose now the question is: what do we do with unsafe blobs? Shall we just extract them as is? That's probably fine, unsafe is just a marker, at the end, performing an unsafe operation resolve to (1) calling unsafe functions or (2) raw pointers. We still reject raw pointers right away, and unsafe functions are just normal functions that usually make strong assumptions, which we can model precisely with strong preconditions

I wonder if we should just turn the unsafe feature on in the F* backend then. Wdyt @franziskuskiefer?

**Comment by franziskuskiefer** [comment]
Sure, let's turn it on for F* and see what happens.
Is more needed than the basic support? If so, please update the issue on what remains unsupported and what's supported. If not, let's close this.

**Comment by W95Psp** [comment]
No, more advanced support would mean library support in the backends, so we should close that issue.
Ok! Will push a PR, it's gonna be a very small PR.
