### ISSUE TITLE
OCaml: add docstrings on modules

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#436]
- [ ] `analyses`
   - [ ] `function_dependency.ml`
   - [ ] `mutable_variables.ml`
 - [ ] `analyses.ml`
 - [ ] `ast.ml`
 - [ ] `ast_utils.ml`
 - [ ] `attr_payloads.ml`
 - [ ] `backend.ml`
 - [ ] `concrete_ident`
   - [ ] `concrete_ident.mli`
   - [ ] `concrete_ident_sig.ml`
   - [ ] `impl_infos.ml`
 - [ ] `dependencies.mli`
 - [ ] `diagnostics.ml`
 - [ ] `feature_gate.ml`
 - [ ] `features.ml`
 - [ ] `generic_printer`
   - [ ] `generic_printer_base.ml`
   - [ ] `generic_printer.mli`
 - [ ] `import_thir.mli`
 - [ ] `local_ident.mli`
 - [ ] `phases`
   - [ ] `phase_and_mut_defsite.mli`
   - [ ] `phase_cf_into_monads.mli`
   - [ ] `phase_direct_and_mut.mli`
   - [ ] `phase_drop_blocks.mli`
   - [ ] `phase_drop_references.mli`
   - [ ] `phase_functionalize_loops.mli`
   - [ ] `phase_local_mutation.mli`
   - [ ] `phase_reconstruct_for_loops.mli`
   - [ ] `phase_reconstruct_question_marks.mli`
   - [ ] `phase_recontruct_for_index_loops.ml`
   - [ ] `phase_reject.ml`
   - [ ] `phase_trivialize_assign_lhs.mli`
 - [ ] `phases.ml`
 - [ ] `phase_utils.ml`
 - [ ] `prelude.ml`
 - [ ] `print_rust.mli`
 - [ ] `side_effect_utils.ml`
 - [ ] `span.mli`
 - [ ] `subtype.ml`
 - [ ] `utils.ml`

**Comment by franziskuskiefer** [comment]
This may indeed be stale... But is some of this needed for #632 ?

**Comment by W95Psp** [comment]
Yes, that's sort of stale.
I wanted to add docs methodically for each module, but finally I'm just adding things progressively while working on things, that never will be complete, but at least that's realistic :sweat_smile: this issue is too optimistic to be any useful I think

Let's close!
