### ISSUE TITLE
[PV/Noise] Provide PV definitions for crypto dependencies

### ISSUE THREAD

**Issue by jschneider-bensch** [hacspec/hax#447]
- [ ]      `Hax_lib_protocol__crypto__hash`
 - [ ]      `Hax_lib_protocol__crypto__hmac`
 - [ ]      `Hax_lib_protocol__crypto__aead_decrypt`
 - [ ]      `Hax_lib_protocol__crypto__aead_encrypt`
 - [ ]      `Hax_lib_protocol__crypto__dh_scalar_multiply`
 - [ ]      `Hax_lib_protocol__crypto__dh_scalar_multiply_base`
 - [ ]      `Hax_lib_protocol__crypto__Impl__from_bytes` (`hax_lib_protocol::cal::impl__DHScalar__from_bytes`)
 - [ ]      `Hax_lib_protocol__crypto__Impl_1__from_bytes` (`hax_lib_protocol::cal::impl__AEADTag__from_bytes`)
 - [ ]      `Hax_lib_protocol__crypto__Impl_4__from_bytes` (`hax_lib_protocol::cal::impl__DHElement__from_bytes`)
 - [ ]      `Hax_lib_protocol__crypto__Impl_5__from_bytes` (`hax_lib_protocol::cal::impl__AEADKey__from_bytes`)
 - [ ]      `Hax_lib_protocol__crypto__Impl_6__from_bytes` (`hax_lib_protocol::cal::impl__AEADIV__from_bytes`)

 - [ ]      `Hax_lib_protocol__crypto__HashAlgorithm__Sha256`
 - [ ]      `Hax_lib_protocol__crypto__DHGroup__X25519`
 - [ ]      `Hax_lib_protocol__crypto__AEADAlgorithm__Chacha20Poly1305`
 - [ ]      `Hax_lib_protocol__crypto__HMACAlgorithm__Sha256`

 - [ ]      `Hax_lib_protocol__crypto__DHScalar`

**Comment by franziskuskiefer** [comment]
The hacspec_lib functions should be replaced by core functions, once that dependency is gone. (Also see comment on #452.)
