### ISSUE TITLE
Add option for marking items as non-export

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#45]
We should have both:
 - CLI options
 - Rust attributes

We should be able to express "everything but foo" and "nothing but foo" (at the module level)

**Comment by franziskuskiefer** [comment]
@W95Psp how does this relate to #211 ?

**Comment by W95Psp** [comment]
I think that's actually a duplicate of https://github.com/hacspec/hacspec-v2/issues/223, which I just added...

**Comment by W95Psp** [comment]
Closed #223 in favor of that one

**Comment by W95Psp** [comment]
Closing this, the feature is there in main.
