### ISSUE TITLE
[ProVerif] Define restrictions on input language

### ISSUE THREAD

**Issue by jschneider-bensch** [hacspec/hax#454]
At the moment, we basically allow any AST feature that's necessary to extract an example which conforms roughly to our idea of a good input and see how to deal with translating it in the backend.
When translation of "known good" examples works reliably, I want to think about which restrictions on the input are really necessary for good translation to ProVerif and which could be addressed by suitable translation phases.

**Comment by W95Psp** [comment]
@jschneider-bensch was this issue supposed to be closed?
