### ISSUE TITLE
[ProVerif] Define abstraction for deserialization

### ISSUE THREAD

**Issue by jschneider-bensch** [hacspec/hax#458]
We want to treat deserialization abstractly in ProVerif, ideally just as a constructor `fun deserialize_X(bitstring) : X.` that we assume will work for deserializing a type `X` (or deserializing into a variant of `X`, more generally).

Then we can annotate our Rust source such that the backend can recognize deserialization code and translate it abstractly as above. Proving correctness of deserialization should be done using another backend.

**Comment by W95Psp** [comment]
@jschneider-bensch was this issue supposed to be closed?
