### ISSUE TITLE
CI: test the frontend (THIR+MIR) on a list of given crate

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#481]
We should put the frontend under CI:
 - [ ] for all our tests and examples
 - [ ] for a list of Rust external crate

Note the tests should extract bodies both as MIR and as THIR.

**Comment by W95Psp** [comment]
Still relevant, and the work is ongoing (@maximebuyse is looking at that!)

**Comment by franziskuskiefer** [comment]
@W95Psp  this looks like we can close it?
