### ISSUE TITLE
More rejected &mut cases

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#490]
A couple of `&mut` cases that hax currently rejects. Some should work and I don't see right away that they should fall into #419.

https://github.com/hacspec/hax/blob/314128f4d627c413fecc89adbf9375da68df93a4/tests/mut-ref-functionalization/src/lib.rs#L105-L149

**Comment by W95Psp** [comment]
Closing this in favor of #491, #492, #493 and #494.
