### ISSUE TITLE
Make `setup.sh` check nodejs version

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#51]
- [x] add a check to script.sh that `node` is in `PATH`
 - [ ] figure out what is the minimal version `VERSION` of nodejs so that `engine/utils/ocaml_of_json_schema/ocaml_of_json_schema.js` works
 - [ ] add a check to script.sh that `node` is at least version `VERSION`

**Comment by franziskuskiefer** [comment]
@georgio can you look into this?

**Comment by franziskuskiefer** [comment]
@georgio do you intend to work on this?
