### ISSUE TITLE
Unexpected provenance in `boringtun` main crate

### ISSUE THREAD

**Issue by RaitoBezarius** [hacspec/hax#578]
On boringtun f672bb6c1e1e371240a8d151f15854687eb740bb and charon 827ee91c945717ca19ae9c3d1cdfa591d0d5e0d9, repo can be found: https://github.com/RaitoBezarius/boringtun/tree/aeneas-fv with a flake.nix for repro.

I tried to build the `boringtun` crate (not the CLI) with `charon --cargo-no-rust-version` (that is, using the same `rustc` as the one `charon` was built with) and got this error:

```
error[HaxFront]: Expected provenance to be GlobalAlloc::Static, got Memory(
                     ConstAllocation { .. },
                 ) instead
  |
  = note: ⚠️ This is a bug in Hax's frontend.
          Please report this error to https://github.com/hacspec/hax/issues with some context (e.g. the current crate)!

error: could not compile `boringtun` (lib) due to previous error
```

**Comment by RaitoBezarius** [comment]
Minimal reproducer:
```
pub(crate) const LABEL_MAC1: &[u8; 8] = b"mac1----";

fn main() {}
```

**Comment by W95Psp** [comment]
Thanks for the bug report!
That's a bug in the MIR extraction of constants, I am going to look into it. Should be easy to fix though, this code extracts without error when exporting THIR.

**Comment by W95Psp** [comment]
I think this was fixed by https://github.com/hacspec/hax/pull/579. Please re-open otherwise.
