### ISSUE TITLE
Alignement between the Rust linter and the actual extraction

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#58]
List of all "un-alignments":
 - [ ] infinite loops

**Please feel free to comment if you notice anything that seems to belong to this list**

**Comment by W95Psp** [comment]
I think we should chat about the linter and what we want to do with it, wdyt @franziskuskiefer, @karthikbhargavan?

**Comment by franziskuskiefer** [comment]
Yeah, the linter really has only been this neglected side project so far. We should integrate it into the rest of the frontend code in a lightweight way that can give us IDE feedback.
But we'll have to talk about what we actually want to do with it and who's doing it etc. In any case we should decide on it early next year and either have a plan to make it useful, or remove it.

**Comment by W95Psp** [comment]
Closing in favor of #610
