### ISSUE TITLE
Core library: F*: support for the `Default` trait

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#585]
hax [doesn't seem to support](https://github.com/future-proof-iot/RIOT-rs/actions/runs/8372464440/job/22923475247?pr=205) Rust's [`Default` trait](https://doc.rust-lang.org/stable/std/default/trait.Default.html). Would it be possible to add support for it?

_Originally posted by @ROMemories in https://github.com/future-proof-iot/RIOT-rs/pull/205#discussion_r1534117627_

**Comment by franziskuskiefer** [comment]
What exactly is failing here? I just tried a simple example with a custom `Default` implementation, [that works](https://hax-playground.cryspen.com/#fstar/9313dbaa10/gist=9c1e600297b2dc3669fe8b82c073e1c3).
Can you post a reproducer for the issue?

**Comment by franziskuskiefer** [comment]
Oh, interesting. Let me re-open and investigate.
