### ISSUE TITLE
Missing const with default value support

### ISSUE THREAD

**Issue by kaspar030** [hacspec/hax#596]
We just hit this:

```
error[HAX0001]: (AST import) something is not implemented yet.
                c_generic_param:Const with a default
  --> src/riot-rs-runqueue/src/runqueue.rs:25:68
   |
25 | pub struct RunQueue<const N_QUEUES: usize, const N_THREADS: usize, const N_CORES: usize = 1> {
   |                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by W95Psp** [comment]
Thanks for the bug report!

Looking a bit at this, I think hax can just ignore such default parameters: whenever the struct will be used, Rust will automatically inline the default value if none was provided.

Will push a PR soon.

**Comment by kaspar030** [comment]
> Will push a PR soon.

Awesome. Thanks for the quick response!
