### ISSUE TITLE
Bounded integers

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#606]
https://crates.io/crates/bounded-integer

**Comment by franziskuskiefer** [comment]
What's the state here? This has been in progress for a while and is supposed to be small and high priority.

**Comment by karthikbhargavan** [comment]
This one is actually small. Let's get it done by tomorrow.

**Comment by W95Psp** [comment]
We just chatted about it:
 - Make `n` variants of the type, `BoundedT`, where T are all the primitive types + int
 - Implement `Deref` for `BoundedT`s

**Comment by W95Psp** [comment]
#643 is required for #642, which in turn will fix this issue
