### ISSUE TITLE
Nat/Int library

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#607]
We want:
 - a type `Int` on which we can do arithmetic from Rust;
 - this type should be a newtype around i128 or bigint;
 - the translation should map to F*'s `int` (or coq `int`), and all operations on `Int` should be mapped to native ones in F*
 - we need to be able to lift machine integers to ints and lift down

**Comment by franziskuskiefer** [comment]
What's the state here? This has been in progress for a while and is supposed to be tiny and high priority.

**Comment by W95Psp** [comment]
There was some progress, but I have been busy doing other stuff...

**Comment by karthikbhargavan** [comment]
After the first two attempts at this, I think this is actually a medium task. 
Also, it is closely linked to the other Integer issues like BoundedInts and SecretInts, so we should do it properly, but soon.
