### ISSUE TITLE
`proverif_before!`, `proverif_after!`, `proverif_replace!` are not working

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#620]
PR #614 adds support for new ways of inlining backend code within Rust.
In the ProVerif backend, certain kinds of items (e.g. Fn vs Type) are outputted in different parts of the output pv files.

I suspect we need to add a `proverif_options` field to `ItemQuote` to allow the user to place the item. Or maybe we should just inherit the position of the item the attribute was on?

@jschneider-bensch what do you think?

**Comment by jschneider-bensch** [comment]
Need to look into the necessary changes a bit more, but should address this, since it would be good to have e.g. when addressing cryspen/bertie#116.

**Comment by W95Psp** [comment]
This was closed by #1023
