### ISSUE TITLE
Implicit Trait Constraints

### ISSUE THREAD

**Issue by karthikbhargavan** [hacspec/hax#622]
When adding a constraint of the form `T: Copy`, rustc always adds a second constraint `T:Copy+Clone`.
Consequently, the generated typeclass in F* has both constraints (to be solved).
However, the corresponding instance (trait implementation) in F* only solved the first constraint, leading to a lax-checking error.

**Comment by W95Psp** [comment]
Requires some investigation, marking it as small for now.

**Comment by W95Psp** [comment]
Seems like I can't reproduce any longer:
```rust
trait T: Clone {
    type U: Clone;    
}
impl T for () {
    type U = ();  
}

fn f<T: Clone>() {}


```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/9313dbaa10/gist=a7d034bd2d4e683985ff9a31b674e53d)
