### ISSUE TITLE
hacspec linter

### ISSUE THREAD

**Issue by franziskuskiefer** [hacspec/hax#63]
Track progress of the hacspec linter, linting for the hacspec subset.

The language definition right now is in [the book](https://hacspec.org/book/language/syntax.html).

- [ ] refine syntax
- [ ] document syntax
- [ ] write syntax tests
- [ ] implement linter for this syntax

**Comment by W95Psp** [comment]
Closing for now, since we did #611. Let's re-open if we want this again.
