### ISSUE TITLE
Frontend crash: ImplExprPredNotFound on bounds on opaque types

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#684]
Reproducer:
```rust
fn uints() -> impl Iterator<Item = u64> {
    vec![0u64].into_iter()
}

fn main() {
    let mut hello = uints();
    hello.next();
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/latest-main/gist=79e3245eef4c026224b317283b165caa)

Crashes with:
```
warning[E9999]: Could not find a clause for `Binder { value: <impl std::iter::Iterator<Item = u64> as std::iter::Iterator>, bound_vars: [] }` in the item parameters
 --> src/lib.rs:5:1
  |
5 | fn main() {
  | ^^^^^^^^^
```

# Solution
We could use `param_env_reveal_all_normalized`, but that would tear down the opaque type abstraction.

**Comment by W95Psp** [comment]
We need to discuss that, I'm not sure this is still an bug.

**Comment by franziskuskiefer** [comment]
[Still seems to crash.](https://hax-playground.cryspen.com/#fstar/16db1cc457/gist=2469dea2facea7e2d032498d1e78167d)

**Comment by W95Psp** [comment]
Ah, thanks for investigating.

**Comment by Nadrieril** [comment]
> We could use param_env_reveal_all_normalized, but that would tear down the opaque type abstraction.

I am personally in favor of that
