### ISSUE TITLE
`-i` flag: allow selection based on visibility

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#688]

**Comment by W95Psp** [comment]
@franziskuskiefer what do you think? it's an enhancement, but I don't know if we care

**Comment by franziskuskiefer** [comment]
Let's throws this onto a doc for potential features if you think it's worth it. Then close it.

**Comment by W95Psp** [comment]
I've documented this in https://github.com/hacspec/hax/issues/497! That's a bit the wishlist for the `i` flag.
