### ISSUE TITLE
Hax hangs on a recursive trait with associated type

### ISSUE THREAD

**Issue by Nadrieril** [hacspec/hax#692]
```rust
pub trait Trait1 {
    type T: Trait1;
}

pub trait Trait2: Trait1 {
    type U;
}
```

Running `hax json` on this code causes it to hang forever. Removing `type U;` fixes the issue.

**Comment by W95Psp** [comment]
This issue stems from the `path_to` function doing a depth-first search.
Doing a breadth-first search instead solves this issue, will push a PR soon.

Note that switching to a breadth-first search is not solving issue #686.
