### ISSUE TITLE
Move the trait resolution to rustc as much as possible

### ISSUE THREAD

**Issue by sonmarcho** [hacspec/hax#706]
Hax re-implements part of the trait resolution because the information provided by rustc is incomplete (see https://doc.rust-lang.org/beta/nightly-rustc/rustc_infer/traits/enum.ImplSource.html where the `Param` variant doesn't tell us exactly how rustc resolved the trait obligation). Redoing this work ourselves it not a good idea because the trait resolution is non-trivial and error-prone: we should find a way of getting the information we need from rustc (potentially by making PRs to rustc).

**Comment by Nadrieril** [comment]
As a small note, because of specialization there may be several impls that can apply in a given context. And std contains a decent amount of specialization. So we'll probably have to handle that.

**Comment by Nadrieril** [comment]
As discussed on Zulip with the compiler team [here](https://rust-lang.zulipchat.com/#narrow/stream/144729-t-types/topic/.E2.9C.94.20Can.20rustc.2Fchalk.20tell.20me.20how.20it.20resolved.20a.20given.20trait.20ref.3F), rustc cannot help us more than it does today. The current implementation (as of https://github.com/hacspec/hax/pull/970) follows their suggestion. I believe we have therefore reached the desired "as much as possible".
