### ISSUE TITLE
Trait selection returns `Unimplemented` on type aliases

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#707]
The frontend fails with `Cannot handle error `Unimplemented` selecting ...` on:

```rust
struct Foo<T: Clone>(T);
type Synonym<T> = Foo<T>;
```

The bug is that Rust doesn't enforce bounds on generic parameters in type aliases.
So writing `type Synonym<T> = Foo<T>;` is legal even if `T` has no bound `Clone`, but hax tries to export an impl source anyway! Obviously, without `T: Clone`, trait selection returns `Unimplemented`.

The solution is not to export impl expressions on type synonyms

Note the following works fine:

```rust
struct Foo<T: Clone>(T);
type Synonym<T: Clone> = Foo<T>;
```

**Comment by franziskuskiefer** [comment]
Note that example that works throws `type_alias_bounds` warnings and therefore should not be used.
