### ISSUE TITLE
Some class parameters are incorrectly passed

### ISSUE THREAD

**Issue by mamonet** [hacspec/hax#719]
In some extracted F* files in `libcrux-ml-kem`, arguments for classes are passed as explicit parameters. For example, `v_K` variable here is supposed to be ghost parameter https://github.com/cryspen/libcrux/blob/dev/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.fst#L89

It's fixed manually in `dev_ml_kem_lax` branch https://github.com/cryspen/libcrux/blob/dev_ml_kem_lax/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.fst#L89

**Comment by mamonet** [comment]
Thanks for fixing this, Lucas.

**Comment by mamonet** [comment]
I will reopen this issue because hax mainstream seems to produce the same kind of error for different modules in libcrux-ml-kem

For example here the parameter of `t_Operations` is suppose to be ghost
https://github.com/cryspen/libcrux/blob/dev_ml_kem_lax/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Traits.fsti#L192
and
https://github.com/cryspen/libcrux/blob/dev_ml_kem_lax/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Polynomial.fsti#L36

**Comment by mamonet** [comment]
The old problems seem to be fixed but nit I got implicit parameters that are supposed to be passed explicitly, here's an example
https://github.com/cryspen/libcrux/blob/dev_ml_kem_lax/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Vector.Traits.fsti#L7-L8

**Comment by mamonet** [comment]
The previous comment was false alert. However, even with PR https://github.com/hacspec/hax/pull/738 I can still instances of this bug.
https://github.com/cryspen/libcrux/blob/dev_ml_kem_lax/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.fst#L90
and
https://github.com/cryspen/libcrux/blob/dev_ml_kem_lax/libcrux-ml-kem/proofs/fstar/extraction/Libcrux_ml_kem.Ind_cca.fst#L225

**Comment by W95Psp** [comment]
Update: I almost fixed it, but got distracted with other things, I will finish that tomorrow morning.
