### ISSUE TITLE
librustc_driver not found when running tests

### ISSUE THREAD

**Issue by maximebuyse** [hacspec/hax#780]
When I run `cargo test --test toolchain`  I get the following error: 
```
/home/maxime/cryspen/hax/target/debug/cargo-hax: error while loading shared libraries: librustc_driver-f4e5b0d07cf2a17f.so: cannot open shared object file: No such file or directory
```
Building hax first and then running `CARGO_TESTS_ASSUME_BUILT=y cargo test --test toolchain -- let-else`  works as a workaround.

**Comment by franziskuskiefer** [comment]
So this is a regression from #743? @W95Psp why aren't there tests catching something like this?

**Comment by W95Psp** [comment]
I don't know whether that's a regression from #743.
I suspect that's a brittle bug that depends on setup. The CI uses this test harness with no problem, @maximebuyse and I need to investigate.

**Comment by W95Psp** [comment]
No one stumbled upon this issue again, it seems, let's close.
