### ISSUE TITLE
Engine: `local_ident`'s `id` type is opaque

### ISSUE THREAD

**Issue by paulmure** [hacspec/hax#850]
The interface for `local_ident` in the engine is defined like this:
```ocaml
  type id [@@deriving show, yojson, hash, compare, sexp, eq]

  val mk_id : kind -> int -> id

  type t = { name : string; id : id }
  [@@deriving show, yojson, hash, compare, sexp, eq]
```
The `id` type is opaque so backends cannot inspect the `kind` of a `local_ident`.

Without this information, certain things become impossible.

**Comment by W95Psp** [comment]
Here I think I have the same concerns as #793: this kind of thing should be used for naming scheme only, what kind of things do you need for local idents?

**Comment by paulmure** [comment]
It’s been a while since I looked at this. IIRC, we needed to inspect the kind to see if a local variable is a const generic (which we treat differently than other local vars).

**Comment by W95Psp** [comment]
Mmh, I see, looks like a legitimate use to me, I can see phases needing such info. Let's merge that PR (finally... I'm sorry --again-- for how long that took...)

**Comment by paulmure** [comment]
No worries, we understand people are busy!

**Comment by W95Psp** [comment]
Thanks for your patience 🙏
