### ISSUE TITLE
Frontend: relative paths are wrong

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#874]
The printing of relative path when the frontend writes files the backend sent is broken. The working directory seems wrong.

Repro:
run `./hax.py extract` on libcrux/libcrux-ml-kem

**Comment by franziskuskiefer** [comment]
@W95Psp is this still an issue?

**Comment by W95Psp** [comment]
I haven't fixed it, but trying to reproduce it, I think that's because the `hax.py` script changes the current directory.

I tried both using Cargo's `-p` flag and `--manifest-path`, things are working fine.

Let's close.
