### ISSUE TITLE
Incorrect line numbers in error messages

### ISSUE THREAD

**Issue by jschneider-bensch** [hacspec/hax#879]
The line numbers on extraction errors don't seem to be correct in all cases.
For example, running `cargo hax into fstar` in the `libcrux-ml-dsa` crate at [this commit](https://github.com/cryspen/libcrux/pull/558/commits/7e674c6d82f120eb174ea98314e356613a85c980) results in a number of errors, e.g.:
```
error: [HAX0010] (RefMut) At this position, Hax was expecting an expression of the shape `&mut _`. Hax forbids `f(x)` (where `f` expects a mutable reference as input) when `x` is not a place expression[1] or when it is a dereference expression.

[1]: https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions

  --> libcrux-ml-dsa/src/encoding/signature.rs:95:1
   |
95 |             hint_serialized[MAX_ONES_IN_HINT + i] = true_hints_seen as u8;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
```
and
```
error: [HAX0010] (RefMut) At this position, Hax was expecting an expression of the shape `&mut _`. Hax forbids `f(x)` (where `f` expects a mutable reference as input) when `x` is not a place expression[1] or when it is a dereference expression.

[1]: https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions

  --> libcrux-ml-dsa/src/encoding/signature.rs:87:1
   |
87 |                     hint_serialized[true_hints_seen] = j as u8;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
```

but these two lines are lines [44](https://github.com/cryspen/libcrux/blob/7e674c6d82f120eb174ea98314e356613a85c980/libcrux-ml-dsa/src/encoding/signature.rs#L44) and [48](https://github.com/cryspen/libcrux/blob/7e674c6d82f120eb174ea98314e356613a85c980/libcrux-ml-dsa/src/encoding/signature.rs#L48) in `signature.rs`, respectively.

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by franziskuskiefer** [comment]
@maximebuyse we've seen this a couple times now. Can you briefly investigate to see if there's a quick fix?

**Comment by maximebuyse** [comment]
Here is a simple example to reproduce: https://hax-playground.cryspen.com/#fstar+tc/5e3e6d2028/gist=8d28897f2b70c279fa560c775d095c17

Seems that the problem was introduced by this commit https://github.com/hacspec/hax/pull/743/commits/df29fbee3cf62ed901d2fd90e0906c4cfdbf9293.

My understanding is that we do something wrong with the `line_start` and the offsets. I still need to figure out exactly what `annotate-snippet` expects here but I should be able to implement a fix quickly.
