### ISSUE TITLE
Frontend: tracing-tree: improve usability

### ISSUE THREAD

**Issue by W95Psp** [hacspec/hax#944]
The traces are super useful for debugging the frontend.
But they also are quite verbose and hard to browse.

Debugging would be much easier if we had a tool to interactively browse traces.

A cheap way of doing that could be to parse the (tree) traces and reshape them as JSON, so that we can `jless` them.

`jless` offers everything we want there: it's super fast, it can search efficiently into data, it's easy to fold the data, etc.

I suspect https://github.com/hacspec/hax/issues/686 is not so hard to fix. But currently, debugging is a huge pain because the logs are hard to browse.

**Comment by franziskuskiefer** [comment]
@W95Psp any updates on this or do you want to push it to next week?

**Comment by W95Psp** [comment]
@Nadrieril actually killed a whole bunch of issues in the frontend, so I don't think this issue is urgent any longer

**Comment by franziskuskiefer** [comment]
Ok, closing then
