### ISSUE TITLE
`'\0'` is translated to incorrect f*

### ISSUE THREAD

**Issue by maximebuyse** [hacspec/hax#993]
The rust character `'\0'` is translated as `'\000'` in f* which is rejected with `unexpected char` by f*.
Writing `0x00 as char` works as a workaround.

**Comment by W95Psp** [comment]
Oh, it seems that it's a bug in the pretty printer of F*

**Comment by W95Psp** [comment]
I opened https://github.com/FStarLang/FStar/issues/3560 on F*. But this will likely be fixed by #942: with that, we won't use F* pretty printer anymore.

**Comment by W95Psp** [comment]
This was closed by #1147
